### ISSUE TITLE
请问为什么Table 4中 PatchCore在Optical上的表现是一条-

### ISSUE THREAD

**Issue by liutongkun** [mala-lab/AHL#1]
很棒的工作，但我想请问一下为什么Table 4中 PatchCore在Optical上的表现是一条-，是因为没有去验证吗还是什么原因呢，谢谢~

**Comment by Diana1026** [comment]
Hi, the size of the optical is too large, and patchcore needs to memorize the whole training set. So my device can't calculate the results.

**Comment by LijialinHub** [comment]
> 很棒的工作，但我想请问一下为什么Table 4中 PatchCore在Optical上的表现是一条-，是因为没有去验证吗还是什么原因呢，谢谢



检测效果究竟如何的 大佬  过检和漏检严重吗？？

**Comment by liutongkun** [comment]
> > 很棒的工作，但我想请问一下为什么Table 4中 PatchCore在Optical上的表现是一条-，是因为没有去验证吗还是什么原因呢，谢谢
> 
> 检测效果究竟如何的 大佬 过检和漏检严重吗？？

我没有试..
